-- 코드를 입력하세요
SELECT t.ANIMAL_ID, t.NAME
FROM (SELECT i.ANIMAL_ID, i.NAME, (o.DATETIME - i.DATETIME) AS PERIOD
FROM ANIMAL_OUTS o 
JOIN ANIMAL_INS i
ON o.ANIMAL_ID = i.ANIMAL_ID) t
ORDER BY PERIOD DESC
LIMIT 2