-- 코드를 입력하세요
WITH t AS (SELECT COUNT(*) AS TOTAL
      FROM USER_INFO u
      WHERE u.JOINED >= '2021-01-01'
      AND u.JOINED < '2022-01-01')
SELECT 
    YEAR(s.SALES_DATE), 
    MONTH(s.SALES_DATE), 
    COUNT(DISTINCT u.USER_ID) AS PURCHASED_USERS, 
    ROUND(COUNT(DISTINCT u.USER_ID)/t.TOTAL, 1) AS PURCHASED_RATIO
FROM ONLINE_SALE s
JOIN USER_INFO u
ON u.USER_ID = s.USER_ID
AND u.JOINED >= '2021-01-01'
AND u.JOINED < '2022-01-01'
JOIN t
ON 1 = 1
GROUP BY YEAR(s.SALES_DATE), MONTH(s.SALES_DATE)