-- 코드를 입력하세요
SELECT p.PRODUCT_ID, p.PRODUCT_NAME, (SUM(AMOUNT) * p.PRICE) AS TOTAL_SALES
FROM FOOD_ORDER o 
JOIN FOOD_PRODUCT p 
ON o.PRODUCT_ID = p.PRODUCT_ID
WHERE PRODUCE_DATE >= '2022-05-01'
AND PRODUCE_DATE < '2022-06-01'
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID