-- 코드를 입력하세요
SELECT DISTINCT c.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR c
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
ON c.CAR_ID = h.CAR_ID
AND h.START_DATE >= '2022-10-01'
AND h.START_DATE < '2022-11-01'
WHERE c.CAR_TYPE = '세단'
ORDER BY c.CAR_ID desc