WITH m AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
SELECT
    i.ID,
    n.FISH_NAME,
    i.LENGTH
FROM FISH_INFO i
JOIN m
  ON i.FISH_TYPE = m.FISH_TYPE
 AND i.LENGTH = m.MAX_LENGTH
JOIN FISH_NAME_INFO n
  ON i.FISH_TYPE = n.FISH_TYPE
ORDER BY i.ID;