-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', b.BOARD_ID, '/', f.FILE_ID, f.FILE_NAME, f.FILE_EXT) AS FILE_PATH
FROM (SELECT BOARD_ID
FROM USED_GOODS_BOARD 
ORDER BY VIEWS desc
LIMIT 1) b
JOIN USED_GOODS_FILE f
ON b.BOARD_ID = f.BOARD_ID
ORDER BY f.FILE_ID desc
